/// Generated by AssetsRefGenerator on 2020/04/29
class Res {
  static const String ball1 = "images/ball1.png";
  static const String ball2 = "images/ball2.png";
  static const String ball3 = "images/ball3.png";
  static const String ball4 = "images/ball4.png";
  static const String ball5 = "images/ball5.png";
}
